config/routes.rb
Rails.application.routes.draw do
  devise_for :users ,controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  root 'dashboards#dashboard'
  resources :authors, only: %i[index new create destroy]
  resources :blogs, only: %i[index new create show destroy] do
    get :autocomplete_blog_title, on: :collection
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
	has_many :blogs, dependent: :destroy
	validates :name, presence: true, uniqueness: true
end

app/models/blog.rb
class Blog < ApplicationRecord
	belongs_to :author
	validates :title, presence: true, uniqueness: true
	has_many :comments,dependent: :destroy
	has_many :pictures, as: :imagable, dependent: :destroy
	accepts_nested_attributes_for :pictures
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog 
  belongs_to :user
end

app/models/picture.rb
class Picture < ApplicationRecord
	mount_uploader :image, ImageUploader
	belongs_to :imagable ,polymorphic: true
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [ :user, :admin ]
  has_one :picture ,as: :imagable,dependent: :destroy
  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :picture
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	
	protected

	def configure_permitted_parameters
	  devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(
	    :email,
	    :password,
	    :password_confirmation,
	    :current_password,
	    picture_attributes: [:image]
	  )}
	end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

	def index
		@authors = Author.all.paginate(page: params[:page], per_page:5)
	end

	def new
		@author= Author.new
	end

	def create
		@author =Author.new(authors_params)
		@author.save
	end

	private
	def authors_params
		params.require(:author).permit(:name)
	end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  autocomplete :blog, :title, full: true

  def index
    if params[:search]
      @blogs = Blog.where("blogs.title LIKE ?", "%#{params[:search]}").paginate(page: params[:page], per_page: 2)
    else
      @blogs = Blog.all.paginate(page: params[:page], per_page: 2)
    end
  end

  def new
    @blog = Blog.new
    @blog.pictures.build
  end

  def create
    @blog = Blog.new(blogs_params)
    if @blog.save
      params[:pictures_attributes]['image'].each do |img|
        @blog.pictures.create(image: img)
      end
    end
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def destroy
    blog_service = DeleteBlog.new(params)
    blog_service.request
    @id = blog_service.blog_id
  end


  private

  def blogs_params
    params.require(:blog).permit(:title, :content, :author_id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@blog =Blog.find(params[:blog_id])
		@comment = @blog.comments.create!(comments_params.merge(user_id: current_user.id))
		redirect_to blog_path(@blog)
	end

	private

	def comments_params
		params.require(:comment).permit(:content)
	end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
	def dashboard
	end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
respond_to :js 
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  respond_to :js
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/authors/_form.html.erb
<div id="AuthorModal" class="modal " role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
         <h2>New Author</h2>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for @author,url: authors_path,validate: true, remote: true  do |f| %>
          <div class="form-group">
            <%= f.input :name, input_html: { class: "form-control", required:true}, input_label: {class: "form-control"} %>
          </div>
          <br>
          <div class="modal-footer">
            <div class="text-center">
              <%= f.button :submit, 'Save',class: 'btn btn-primary' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/authors/_list.html.erb
<div class="container">
  <div class="well">
    <div class="media">
    	<div class="media-body">
				<p><%= author.name%></p>
			</div>
		</div>
	</div>
</div>

app/views/authors/create.js.erb
$('#newAuthorLink').show()
$('.new-form').html("")
$('.jsAuthorList').append("<%= j render partial: 'authors/list', locals: {author: @author}%> ")

app/views/authors/index.html.erb
<div class="container-fluid">
	<h3 class="text-center">AUTHOR PAGE</h3>
	<div class="jsAuthorList">
		<%= render partial: 'list', collection: @authors, as: :author %>
	</div>
	<br>
	<div class= "new-form"></div>
	<div id="newAuthorLink">
		<%= link_to 'New Author', new_author_path, remote: true, class:'btn btn-primary' %> 
	</div>
	<div>
		<%= will_paginate @authors%>
	</div>
</div>

app/views/authors/new.js.erb
console.log("hello");
// $('#newAuthorLink').hide()
$('.new-form').html("<%= j render partial: 'form' %>")
$("#AuthorModal").modal('show');

app/views/blogs/_form.html.erb
<div id="BlogModal" class="modal " role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
         <h2>New Blog</h2>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for @blog,url: blogs_path,html: {multipart: :true}, remote: true  do |f| %>
        <%= f.error_notification %>
          <div class="form-group">
            <%= f.input :title, input_html: { class: "form-control", required: true}, input_label: {class: "form-control"} %>
          </div>
          <br>
          <div class="form-group">
            <%= f.input :content, as: :trix_editor, input_html: {class: "form-control"}, input_label: {class: "form-control"}   %>
          </div>
          <br>
          <div class="form-group">
            <%= f.association :author, collection: Author.order(:name), input_html: { class: "form-control", required: true}, input_label: {class: "form-control"}   %>
          </div>
          <br>
          <%= f.fields_for :pictures do |b| %>
            <div class="form-group">
              <%= b.input :image, as: :file, input_html: { class: "form-control", multiple: true, name: "pictures_attributes[image][]"}, input_label: {class: "form-control"} %>
            </div>
          <% end %>
          <br>
          <div class="modal-footer">
            <div class="text-center">
              <%= f.button :submit,'Save', class: 'btn btn-primary' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/blogs/_list.html.erb
<div class="container">
  <div class="well">
    <div class="media">
      <%# blog.pictures.each do |img|  %>
        <%#= image_tag img.image_url, style: 'height:15rem;width:20rem;', class:'pull-left' %>
      <%# end %>
      <div class="media-body">
        <h2 class="media-heading"><%= blog.title %></h2>
        <p class="text-right"><%= blog.author.name %></p>
        <p><h5><%= blog.content.html_safe %></h5></p>
        <ul class="list-inline list-unstyled">
          <li>
            <span>
              <%= link_to 'Show',blog, class: 'btn btn-primary'%>
            </span>
          </li>
          <li>|</li>
          <li>
            <span>
              <%= link_to 'Delete', blog, method: :delete, data: { confirm: 'Are you sure?' }, remote: true, class:'btn btn-primary'%>        
            </span>
          </li>
            <li>|</li>
            <li>
              <span><i class="glyphicon glyphicon-comment"></i> <%= blog.comments.count%> comments</span>
            </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/blogs/create.js.erb
$('#newBlogLink').show()
$('.new-form').html("")
$('.jsBlogList').append("<%= j render partial: 'blogs/list', locals: {blog: @blog}%> ")

app/views/blogs/index.html.erb
<div class="container">
	<h3 class="text-center">BLOG PAGE</h3>
	<div class="container-fluid">
		<div class="container-fluid">
			<form action="<%= blogs_path %>">
				<div id="searchComplete">
		  		<input type="text" placeholder="Search blogs by title" name="search" style="width:20rem;" class="auto-suggestion" autocomplete="on">
		  		<button type="submit">Search</button>
		  	</div>
		  </form>
		</div>
		<br>
		<div class="jsBlogList">
			<%= render partial: 'list', collection: @blogs, as: :blog %>
		</div>
		
		<div id= "newBlogLink">
			<%= link_to 'Add Blog', new_blog_path, remote:true, class:'btn btn-primary'%>
		</div>
		<div class= "new-form"></div>
	</div>
	<div class="pagination">
		<%= will_paginate @blogs %>
	</div>
</div>
<script>
  initSuggestion()
</script>

app/views/blogs/new.js.erb
console.log("hii");
$('#newBlogLink').hide()
$('.new-form').html("<%= j render partial: 'form' %>")
$("#BlogModal").modal('show');

app/views/blogs/show.html.erb
<div class="container-fluid">
  <h3><%#=@blog.title%></h3>
  <div class="slideshow-container">
    <% @blog.pictures.each do |img|  %>
      <div class="mySlides">
        <%= image_tag img.image_url,style:'width:100%;'%>
      </div>
    <% end %>
    <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
    <a class="next" onclick="plusSlides(1)">&#10095;</a>
  </div>
  <br>
  <div class="card">
    <div class="card-body">
      <h5><%= @blog.content.html_safe%></h5>
    </div>
  </div>
  <h3>Comments</h3>
  <div class="card" style="width: 21rem;">
    <div class="card-body">
      <%= render @blog.comments %>
    </div>
  </div>
  <h3>Leave a reply</h3>
  <div class="card" style="width: 21rem;">
    <div class="card-body">
      <%= render 'comments/form' %>
    </div>
  </div>
  <br>
  <%= link_to 'Back',blogs_path, class:'btn btn-primary'%> 
</div>  

app/views/comments/_comment.html.erb
<p><%= comment.content %></p>

app/views/comments/_form.html.erb
<div>
  <%= simple_form_for([@blog, @blog.comments.build]) do |f| %>
    <div class="control">
      <%= f.input :content, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label' }  %>
    </div>
    <br>
    <div class="control">     
      <%= f.button :submit, 'Leave a reply', class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/comments/index.html.erb
<h1> Comment</h1>

app/views/dashboards/dashboard.html.erb
<h1>Dashboard</h1>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>